default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:

development:
  <<: *default
  database: poapapp_api_development

test:
  <<: *default
  database: poapapp_api_test

production:
  <<: *default
  database: heroku_6278e56f5b9acb7
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>